# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171123_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addres',
            new_name='address',
        ),
    ]
