# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171123_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_purchases',
            field=models.IntegerField(default=0),
        ),
    ]
