# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_number_of_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postavshik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'postavshik',
                'verbose_name_plural': 'postavshik',
            },
        ),
    ]
